### ISSUE TITLE
Removed the deprecatd class "TrackUtils" used in StartRecording.java

### ISSUE THREAD

**Issue by sdsameer** [Vaibhav2399/OpenTracks-Winter-SOEN-6431_2024#17]
**Technical Debt Description**
The "TrackUtils" class is marked as deprecated, which means it is no longer recommended for use and may be removed in future releases. Ignoring deprecation warnings can lead to potential issues and reduced code maintainability.
![WhatsApp Image 2024-02-16 at 12 55 25 PM](https://github.com/Vaibhav2399/OpenTracks-Winter-SOEN-6431_2024/assets/51773587/54e7d3d4-b67e-405d-b49b-cb5776f1f67d)

**Proposed Solution**
I Replaced the usage of the deprecated "TrackUtils" class with the ContentProviderUtils.java. I Updated the code to use the new approach to ensure compatibility, adherence to best practices, and maintainability.
![WhatsApp Image 2024-02-16 at 12 55 25 PM (1)](https://github.com/Vaibhav2399/OpenTracks-Winter-SOEN-6431_2024/assets/51773587/d2c31385-405f-4632-b474-b5dc37655eab)

**Commit ID :**  https://github.com/Vaibhav2399/OpenTracks-Winter-SOEN-6431_2024/pull/14/commits/509f7833ea1107f3dfcfbb604b3001796ef6276b

**Comment by DP8801** [comment]
Done successfully.
